version: "3.9"
services:
  db:
    container_name: DBOneGed
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - dbOneGed:/var/lib/mysql
volumes:
  dbOneGed:
