version: "3.9"
services:
  db:
    container_name: SpringTweet
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - dbSpringTweet:/var/lib/mysql
volumes:
  dbSpringTweet:
